parameters:
    preview_icons:
        pdf: 'dropzone-file.png'
        unknown: 'default.png'

services:
    media:
        class: Alpixel\Bundle\MediaBundle\Services\MediaManager
        arguments:    [@doctrine, @kernel, %media.upload_folder%, %media.allowed_mimetypes%]

    twig.extension.media:
      class: Alpixel\Bundle\MediaBundle\Twig\Extension\MediaExtension
      arguments: [@media]
      tags:
          - { name: twig.extension }

    twig.extension.media_preview_extension:
        class: Alpixel\Bundle\MediaBundle\Twig\Extension\MediaPreviewExtension
        arguments: [@request_stack, @doctrine.orm.default_entity_manager, %preview_icons%]
        tags:
            - { name: twig.extension }

    media.admin.admin_media:
        class: Alpixel\Bundle\MediaBundle\Admin\AdminMedia
        arguments: [~, Alpixel\Bundle\MediaBundle\Entity\Media, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, show_in_dashboard: false, manager_type: orm, group: admin, label: Media}

    media.type:
        class: Alpixel\Bundle\MediaBundle\Form\MediaType
        arguments: [@doctrine, @event_dispatcher]
        tags:
            - { name: form.type, alias: media }

    media.listener.media:
        class: Alpixel\Bundle\MediaBundle\EventListener\MediaListener
        arguments: [@doctrine]
        tags:
            - { name: kernel.event_listener, event: 'alpixel.media.post_submit', method: onPostSubmit }
